from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    # ex. /
    path("", views.index, name='index'),
    # ex. /login
    path("login", views.login_user, name='login'),
    # ex. /logout
    path("logout", views.logout_user, name='logout'),
    # ex. /register
    path("register", views.register, name='register'),
    # ex. /profile
    path("profile", views.profile, name='profile'),
    # ex. /profile/edit
    path("profile/edit", views.edit_profile, name='edit_profile'),
    # ex. /profile/edit
    path("profile/edit/password", views.change_password, name='change_password'),
    # ex. /pets
    path("pets", views.available_animals, name='pets'),
    # ex. /pets/search
    path("pets/search", views.available_animals_search, name='search_pets'),
    # ex. /pets/edit/1
    path("pets/edit/<int:animal_id>", views.animal_edit, name='animal_edit'),
    # ex. /pets/details/1
    path("pets/details/<int:animal_id>", views.animal_detail, name='animal_detail'),
    # ex. /new_arrival
    path("new_arrival", views.new_arrival, name='new_arrival'),
    # ex. /pets/adopt/1
    path("pets/adopt/<int:id>", views.adoption_app, name='adopt'),
    # ex. /adoptions/all
    path("adoptions/all", views.list_animals, name='list_applications'),
    # ex. /adoptions/1
    path("adoptions/pet/<int:id>", views.list_specific_applications, name='list_specific_applications'),
    # ex. /adoptions/1/final
    path("adoptions/pet/<int:animal_id>/final/app_id=<int:application_id>", views.final_decision, name='final_decision'),
    # ex. /adoptions/1/final/reject/app_id=1
    path("adoptions/pet/<int:animal_id>/reject/app_id=<int:application_id>", views.reject_application, name='reject_application'),
    # ex. /adoptions/1/final/revise/app_id=1
    path("adoptions/pet/<int:animal_id>/revise/app_id=<int:application_id>", views.revise_judgment, name='revise_judgment'),
    # ex. /volunteering/all
    path("volunteering/all", views.list_volunteering, name='list_volunteering'),
    # ex. /volunteering/new
    path("volunteering/new", views.add_volunteering, name='add_volunteering'),
    # ex. /volunteering/edit/1
    path("volunteering/edit/<int:activity_id>", views.edit_volunteering, name='edit_volunteering'),
    # ex. /volunteering/details/1
    path("volunteering/details/<int:activity_id>", views.volunteering_details, name='volunteering_details'),
    # ex. /volunteering/signup/1
    path("volunteering/signup/<int:activity_id>", views.volunteering_signup, name='volunteering_signup'),
    # ex. /volunteering/cancel/1
    path("volunteering/cancel/<int:activity_id>", views.cancel_volunteering, name='cancel_volunteering'),
]